version: "3.8"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: tara
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/app
    env_file: 
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  pgdata:
